const colors = {
  light: {
    text: '#0A0E1A',
    tint: '#7B6CF8',
    background: '#F4F6FC',
    foreground: '#0A0E1A',
    card: '#FFFFFF',
    cardForeground: '#0A0E1A',
    primary: '#7B6CF8',
    primaryForeground: '#FFFFFF',
    secondary: '#EEF0FF',
    secondaryForeground: '#7B6CF8',
    muted: '#F0F2F8',
    mutedForeground: '#8B96B0',
    accent: '#00C896',
    accentForeground: '#FFFFFF',
    destructive: '#FF4757',
    destructiveForeground: '#FFFFFF',
    border: '#E4E8F0',
    input: '#E4E8F0',
  },
  dark: {
    text: '#F0F2FC',
    tint: '#9D8FF8',
    background: '#0A0E1A',
    foreground: '#F0F2FC',
    card: '#151C2E',
    cardForeground: '#F0F2FC',
    primary: '#9D8FF8',
    primaryForeground: '#0A0E1A',
    secondary: '#1A2235',
    secondaryForeground: '#B0B8D8',
    muted: '#1A2235',
    mutedForeground: '#6B7894',
    accent: '#00D9A6',
    accentForeground: '#0A0E1A',
    destructive: '#FF4757',
    destructiveForeground: '#FFFFFF',
    border: '#1E2840',
    input: '#1E2840',
  },
  radius: 14,
};

export default colors;
